name: Overseerr
version: 0.1.0.2
slug: overseerr
description: Request management and media discovery tool for the Plex ecosystem
url: https://github.com/jaws35smith/hassio-repository-test/blob/master/overseerr/README.md
ingress: true
ingress_port: 5055
ingress_stream: true
init: false
arch:
  - aarch64
  - amd64
  - armv7
map:
  - addon_config:rw
  - share:rw
  - media:rw
image: ghcr.io/hassio-addons/overseerr/{arch}

environment:
  OVERSEERR_HOST: "0.0.0.0"
  OVERSEERR_PORT: "5055"
